version: "3.9"
services:
    poll:
      restart: always
      build: ./poll
      ports:
        - "5000:80"
      networks:
        - poll-tier
      environment:
        - host=0.0.0.0
        - port=80
    redis:
      restart: always
      image: redis
      ports:
        - "6379:6379"
      networks:
        - poll-tier
        - back-tier
      depends_on:
        - "db"
    worker:
      restart: always
      build: ./worker
      networks:
        - back-tier
      environment:
        - host_redis=redis
        - host_db=db
      depends_on:
        - "redis"
        - "db"
    db:
      restart: always
      image: postgres:9.4
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      volumes:
        - db-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      networks:
        - result-tier
        - back-tier
    result:
      restart: always
      build: ./result
      ports:
        - "5001:80"
      networks:
        - result-tier
      environment:
        - port=80
      depends_on:
        - "db"

volumes:
  db-data:

networks:
  poll-tier:
    external:
      name: poll-tier
  result-tier:
    external:
      name: result-tier
  back-tier:
    external:
      name: back-tier